docs:
  - changed-files:
    - any-glob-to-any-file:
      - docs/**/*
      - docs_src/**/*

internal:
  - changed-files:
    - any-glob-to-any-file:
      - .github/**/*
      - scripts/**/*
      - .gitignore
      - .pre-commit-config.yaml
      - pdm_build.py
      - requirements*.txt
