name: Issue Manager

on:
  schedule:
    - cron: "13 21 * * *"
  issue_comment:
    types:
      - created
  issues:
    types:
      - labeled
  pull_request_target: # zizmor: ignore[dangerous-triggers]
    types:
      - labeled
  workflow_dispatch:

permissions: {}

jobs:
  issue-manager:
    if: github.repository_owner == 'fastapi'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    timeout-minutes: 5
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: tiangolo/issue-manager@48bacd85fb842cc27efee25e834edb00aad8f263 # 0.8.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
