name: Publish

on:
  release:
    types:
      - created
  # TODO: remove this
  push:
    branches:
      - typer-slim

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package_dir:
          - ./
          - typer_package
          - typer_cli_package
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          # Issue ref: https://github.com/actions/setup-python/issues/436
          # cache: "pip"
          # cache-dependency-path: pyproject.toml
      - name: Install build dependencies
        run: pip install build
      - name: Build distribution
        working-directory: ${{ matrix.package_dir }}
        run: python -m build
      - name: Publish
        uses: pypa/gh-action-pypi-publish@v1.8.11
        with:
          # TODO: uncomment this
          # password: ${{ secrets.PYPI_API_TOKEN }}
          # TODO: remove this
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
          packages-dir: ${{ matrix.package_dir }}/dist/
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
